"""autogenerated by genpy from markerHandlerServer/get_markerRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class get_markerRequest(genpy.Message):
  _md5sum = "63fef0c7b12971ed9ff30d60b608327a"
  _type = "markerHandlerServer/get_markerRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """std_msgs/String get_marker_req

================================================================================
MSG: std_msgs/String
string data

"""
  __slots__ = ['get_marker_req']
  _slot_types = ['std_msgs/String']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       get_marker_req

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(get_markerRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.get_marker_req is None:
        self.get_marker_req = std_msgs.msg.String()
    else:
      self.get_marker_req = std_msgs.msg.String()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.get_marker_req.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.get_marker_req is None:
        self.get_marker_req = std_msgs.msg.String()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.get_marker_req.data = str[start:end].decode('utf-8')
      else:
        self.get_marker_req.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.get_marker_req.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.get_marker_req is None:
        self.get_marker_req = std_msgs.msg.String()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.get_marker_req.data = str[start:end].decode('utf-8')
      else:
        self.get_marker_req.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
"""autogenerated by genpy from markerHandlerServer/get_markerResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import markerHandlerServer.msg
import std_msgs.msg

class get_markerResponse(genpy.Message):
  _md5sum = "5875797261019cdd26559925dae1e665"
  _type = "markerHandlerServer/get_markerResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """environment_marker get_marker_res
bool is_marker_exist


================================================================================
MSG: markerHandlerServer/environment_marker
std_msgs/String name
geometry_msgs/PoseStamped pose

================================================================================
MSG: std_msgs/String
string data

================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

"""
  __slots__ = ['get_marker_res','is_marker_exist']
  _slot_types = ['markerHandlerServer/environment_marker','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       get_marker_res,is_marker_exist

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(get_markerResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.get_marker_res is None:
        self.get_marker_res = markerHandlerServer.msg.environment_marker()
      if self.is_marker_exist is None:
        self.is_marker_exist = False
    else:
      self.get_marker_res = markerHandlerServer.msg.environment_marker()
      self.is_marker_exist = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.get_marker_res.name.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.get_marker_res.pose.header.seq, _x.get_marker_res.pose.header.stamp.secs, _x.get_marker_res.pose.header.stamp.nsecs))
      _x = self.get_marker_res.pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7dB.pack(_x.get_marker_res.pose.pose.position.x, _x.get_marker_res.pose.pose.position.y, _x.get_marker_res.pose.pose.position.z, _x.get_marker_res.pose.pose.orientation.x, _x.get_marker_res.pose.pose.orientation.y, _x.get_marker_res.pose.pose.orientation.z, _x.get_marker_res.pose.pose.orientation.w, _x.is_marker_exist))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.get_marker_res is None:
        self.get_marker_res = markerHandlerServer.msg.environment_marker()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.get_marker_res.name.data = str[start:end].decode('utf-8')
      else:
        self.get_marker_res.name.data = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.get_marker_res.pose.header.seq, _x.get_marker_res.pose.header.stamp.secs, _x.get_marker_res.pose.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.get_marker_res.pose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.get_marker_res.pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 57
      (_x.get_marker_res.pose.pose.position.x, _x.get_marker_res.pose.pose.position.y, _x.get_marker_res.pose.pose.position.z, _x.get_marker_res.pose.pose.orientation.x, _x.get_marker_res.pose.pose.orientation.y, _x.get_marker_res.pose.pose.orientation.z, _x.get_marker_res.pose.pose.orientation.w, _x.is_marker_exist,) = _struct_7dB.unpack(str[start:end])
      self.is_marker_exist = bool(self.is_marker_exist)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.get_marker_res.name.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.get_marker_res.pose.header.seq, _x.get_marker_res.pose.header.stamp.secs, _x.get_marker_res.pose.header.stamp.nsecs))
      _x = self.get_marker_res.pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7dB.pack(_x.get_marker_res.pose.pose.position.x, _x.get_marker_res.pose.pose.position.y, _x.get_marker_res.pose.pose.position.z, _x.get_marker_res.pose.pose.orientation.x, _x.get_marker_res.pose.pose.orientation.y, _x.get_marker_res.pose.pose.orientation.z, _x.get_marker_res.pose.pose.orientation.w, _x.is_marker_exist))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.get_marker_res is None:
        self.get_marker_res = markerHandlerServer.msg.environment_marker()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.get_marker_res.name.data = str[start:end].decode('utf-8')
      else:
        self.get_marker_res.name.data = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.get_marker_res.pose.header.seq, _x.get_marker_res.pose.header.stamp.secs, _x.get_marker_res.pose.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.get_marker_res.pose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.get_marker_res.pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 57
      (_x.get_marker_res.pose.pose.position.x, _x.get_marker_res.pose.pose.position.y, _x.get_marker_res.pose.pose.position.z, _x.get_marker_res.pose.pose.orientation.x, _x.get_marker_res.pose.pose.orientation.y, _x.get_marker_res.pose.pose.orientation.z, _x.get_marker_res.pose.pose.orientation.w, _x.is_marker_exist,) = _struct_7dB.unpack(str[start:end])
      self.is_marker_exist = bool(self.is_marker_exist)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_7dB = struct.Struct("<7dB")
class get_marker(object):
  _type          = 'markerHandlerServer/get_marker'
  _md5sum = 'd62e1f91bc04d0354277ab016cadfd60'
  _request_class  = get_markerRequest
  _response_class = get_markerResponse
