"""autogenerated by genpy from markerHandlerServer/set_markerRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class set_markerRequest(genpy.Message):
  _md5sum = "14f2c861bcd995b45367312c6e1b6cae"
  _type = "markerHandlerServer/set_markerRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """std_msgs/String marker_name


std_msgs/Bool use_custom_pose
geometry_msgs/PoseStamped marker_pose

================================================================================
MSG: std_msgs/String
string data

================================================================================
MSG: std_msgs/Bool
bool data
================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

"""
  __slots__ = ['marker_name','use_custom_pose','marker_pose']
  _slot_types = ['std_msgs/String','std_msgs/Bool','geometry_msgs/PoseStamped']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       marker_name,use_custom_pose,marker_pose

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(set_markerRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.marker_name is None:
        self.marker_name = std_msgs.msg.String()
      if self.use_custom_pose is None:
        self.use_custom_pose = std_msgs.msg.Bool()
      if self.marker_pose is None:
        self.marker_pose = geometry_msgs.msg.PoseStamped()
    else:
      self.marker_name = std_msgs.msg.String()
      self.use_custom_pose = std_msgs.msg.Bool()
      self.marker_pose = geometry_msgs.msg.PoseStamped()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.marker_name.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_B3I.pack(_x.use_custom_pose.data, _x.marker_pose.header.seq, _x.marker_pose.header.stamp.secs, _x.marker_pose.header.stamp.nsecs))
      _x = self.marker_pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.marker_pose.pose.position.x, _x.marker_pose.pose.position.y, _x.marker_pose.pose.position.z, _x.marker_pose.pose.orientation.x, _x.marker_pose.pose.orientation.y, _x.marker_pose.pose.orientation.z, _x.marker_pose.pose.orientation.w))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.marker_name is None:
        self.marker_name = std_msgs.msg.String()
      if self.use_custom_pose is None:
        self.use_custom_pose = std_msgs.msg.Bool()
      if self.marker_pose is None:
        self.marker_pose = geometry_msgs.msg.PoseStamped()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.marker_name.data = str[start:end].decode('utf-8')
      else:
        self.marker_name.data = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.use_custom_pose.data, _x.marker_pose.header.seq, _x.marker_pose.header.stamp.secs, _x.marker_pose.header.stamp.nsecs,) = _struct_B3I.unpack(str[start:end])
      self.use_custom_pose.data = bool(self.use_custom_pose.data)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.marker_pose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.marker_pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.marker_pose.pose.position.x, _x.marker_pose.pose.position.y, _x.marker_pose.pose.position.z, _x.marker_pose.pose.orientation.x, _x.marker_pose.pose.orientation.y, _x.marker_pose.pose.orientation.z, _x.marker_pose.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.marker_name.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_B3I.pack(_x.use_custom_pose.data, _x.marker_pose.header.seq, _x.marker_pose.header.stamp.secs, _x.marker_pose.header.stamp.nsecs))
      _x = self.marker_pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.marker_pose.pose.position.x, _x.marker_pose.pose.position.y, _x.marker_pose.pose.position.z, _x.marker_pose.pose.orientation.x, _x.marker_pose.pose.orientation.y, _x.marker_pose.pose.orientation.z, _x.marker_pose.pose.orientation.w))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.marker_name is None:
        self.marker_name = std_msgs.msg.String()
      if self.use_custom_pose is None:
        self.use_custom_pose = std_msgs.msg.Bool()
      if self.marker_pose is None:
        self.marker_pose = geometry_msgs.msg.PoseStamped()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.marker_name.data = str[start:end].decode('utf-8')
      else:
        self.marker_name.data = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.use_custom_pose.data, _x.marker_pose.header.seq, _x.marker_pose.header.stamp.secs, _x.marker_pose.header.stamp.nsecs,) = _struct_B3I.unpack(str[start:end])
      self.use_custom_pose.data = bool(self.use_custom_pose.data)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.marker_pose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.marker_pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.marker_pose.pose.position.x, _x.marker_pose.pose.position.y, _x.marker_pose.pose.position.z, _x.marker_pose.pose.orientation.x, _x.marker_pose.pose.orientation.y, _x.marker_pose.pose.orientation.z, _x.marker_pose.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_7d = struct.Struct("<7d")
_struct_B3I = struct.Struct("<B3I")
"""autogenerated by genpy from markerHandlerServer/set_markerResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class set_markerResponse(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "markerHandlerServer/set_markerResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """


"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(set_markerResponse, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
class set_marker(object):
  _type          = 'markerHandlerServer/set_marker'
  _md5sum = '14f2c861bcd995b45367312c6e1b6cae'
  _request_class  = set_markerRequest
  _response_class = set_markerResponse
